export const GET_CURRENCIES = "GET_CURRENCIES";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAIL = "GET_CURRENCIES_FAIL";

export const GET_CURRENCY_RATES = "GET_CURRENCY_RATES";
export const GET_CURRENCY_RATES_SUCCESS = "GET_CURRENCY_RATES_SUCCESS";
export const GET_CURRENCY_RATES_FAIL = "GET_CURRENCY_RATES_FAIL";